// This file is auto-generated by @hey-api/openapi-ts

export { householdMine, type Options } from './sdk.gen';
export type {
    ClientOptions,
    HouseholdDto,
    HouseholdMineData,
    HouseholdMineResponse,
    HouseholdMineResponses,
} from './types.gen';
