// This file is auto-generated by @hey-api/openapi-ts

import type {
    Client,
    ClientMeta,
    Options as Options2,
    RequestResult,
    TDataShape,
} from './client';
import { client } from './client.gen';
import type {
    CategoryCreateCategoryData,
    CategoryCreateCategoryResponses,
    CategoryDeleteCategoryData,
    CategoryDeleteCategoryResponses,
    CategoryGetCategoriesData,
    CategoryGetCategoriesResponses,
    CategoryUpdateCategoryData,
    CategoryUpdateCategoryResponses,
    HouseholdMineData,
    HouseholdMineResponses,
} from './types.gen';

export type Options<
    TData extends TDataShape = TDataShape,
    ThrowOnError extends boolean = boolean,
    TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never
        ? Record<string, unknown>
        : ClientMeta;
};

export const householdMine = <ThrowOnError extends boolean = false>(
    options?: Options<HouseholdMineData, ThrowOnError>,
): RequestResult<HouseholdMineResponses, unknown, ThrowOnError> =>
    (options?.client ?? client).get<
        HouseholdMineResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                in: 'cookie',
                name: 'better-auth.session_token',
                type: 'apiKey',
            },
        ],
        url: '/api/households/me',
        ...options,
    });

export const categoryGetCategories = <ThrowOnError extends boolean = false>(
    options: Options<CategoryGetCategoriesData, ThrowOnError>,
): RequestResult<CategoryGetCategoriesResponses, unknown, ThrowOnError> =>
    (options.client ?? client).get<
        CategoryGetCategoriesResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                in: 'cookie',
                name: 'better-auth.session_token',
                type: 'apiKey',
            },
        ],
        url: '/api/households/{householdId}/categories',
        ...options,
    });

export const categoryCreateCategory = <ThrowOnError extends boolean = false>(
    options: Options<CategoryCreateCategoryData, ThrowOnError>,
): RequestResult<CategoryCreateCategoryResponses, unknown, ThrowOnError> =>
    (options.client ?? client).post<
        CategoryCreateCategoryResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                in: 'cookie',
                name: 'better-auth.session_token',
                type: 'apiKey',
            },
        ],
        url: '/api/households/{householdId}/categories',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

export const categoryDeleteCategory = <ThrowOnError extends boolean = false>(
    options: Options<CategoryDeleteCategoryData, ThrowOnError>,
): RequestResult<CategoryDeleteCategoryResponses, unknown, ThrowOnError> =>
    (options.client ?? client).delete<
        CategoryDeleteCategoryResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                in: 'cookie',
                name: 'better-auth.session_token',
                type: 'apiKey',
            },
        ],
        url: '/api/households/{householdId}/categories/{categoryId}',
        ...options,
    });

export const categoryUpdateCategory = <ThrowOnError extends boolean = false>(
    options: Options<CategoryUpdateCategoryData, ThrowOnError>,
): RequestResult<CategoryUpdateCategoryResponses, unknown, ThrowOnError> =>
    (options.client ?? client).patch<
        CategoryUpdateCategoryResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                in: 'cookie',
                name: 'better-auth.session_token',
                type: 'apiKey',
            },
        ],
        url: '/api/households/{householdId}/categories/{categoryId}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });
