// This file is auto-generated by @hey-api/openapi-ts

import type {
    Client,
    ClientMeta,
    Options as Options2,
    RequestResult,
    TDataShape,
} from './client';
import { client } from './client.gen';
import type {
    AccountCreateAccountData,
    AccountCreateAccountResponses,
    AccountDeleteAccountData,
    AccountDeleteAccountResponses,
    AccountGetAccountsData,
    AccountGetAccountsResponses,
    AccountUpdateAccountData,
    AccountUpdateAccountResponses,
    CategoryCreateCategoryData,
    CategoryCreateCategoryResponses,
    CategoryDefaultsGetDefaultCategoriesData,
    CategoryDefaultsGetDefaultCategoriesResponses,
    CategoryDeleteCategoryData,
    CategoryDeleteCategoryResponses,
    CategoryGetCategoriesData,
    CategoryGetCategoriesResponses,
    CategoryUpdateCategoryData,
    CategoryUpdateCategoryResponses,
    HouseholdMineData,
    HouseholdMineResponses,
    OnboardingOnboardData,
    OnboardingOnboardResponses,
    OnboardingValidateAccountsData,
    OnboardingValidateAccountsResponses,
    OnboardingValidateCategoriesData,
    OnboardingValidateCategoriesResponses,
    OnboardingValidateHouseholdData,
    OnboardingValidateHouseholdResponses,
    TransactionCreateTransactionData,
    TransactionCreateTransactionResponses,
    TransactionDeleteTransactionData,
    TransactionDeleteTransactionResponses,
    TransactionGetTransactionsData,
    TransactionGetTransactionsResponses,
    TransactionUpdateTransactionData,
    TransactionUpdateTransactionResponses,
} from './types.gen';

export type Options<
    TData extends TDataShape = TDataShape,
    ThrowOnError extends boolean = boolean,
    TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never
        ? Record<string, unknown>
        : ClientMeta;
};

export const householdMine = <ThrowOnError extends boolean = false>(
    options?: Options<HouseholdMineData, ThrowOnError>,
): RequestResult<HouseholdMineResponses, unknown, ThrowOnError> =>
    (options?.client ?? client).get<
        HouseholdMineResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                in: 'cookie',
                name: 'better-auth.session_token',
                type: 'apiKey',
            },
        ],
        url: '/api/households/me',
        ...options,
    });

export const categoryGetCategories = <ThrowOnError extends boolean = false>(
    options: Options<CategoryGetCategoriesData, ThrowOnError>,
): RequestResult<CategoryGetCategoriesResponses, unknown, ThrowOnError> =>
    (options.client ?? client).get<
        CategoryGetCategoriesResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                in: 'cookie',
                name: 'better-auth.session_token',
                type: 'apiKey',
            },
        ],
        url: '/api/households/{householdId}/categories',
        ...options,
    });

export const categoryCreateCategory = <ThrowOnError extends boolean = false>(
    options: Options<CategoryCreateCategoryData, ThrowOnError>,
): RequestResult<CategoryCreateCategoryResponses, unknown, ThrowOnError> =>
    (options.client ?? client).post<
        CategoryCreateCategoryResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                in: 'cookie',
                name: 'better-auth.session_token',
                type: 'apiKey',
            },
        ],
        url: '/api/households/{householdId}/categories',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

export const categoryDeleteCategory = <ThrowOnError extends boolean = false>(
    options: Options<CategoryDeleteCategoryData, ThrowOnError>,
): RequestResult<CategoryDeleteCategoryResponses, unknown, ThrowOnError> =>
    (options.client ?? client).delete<
        CategoryDeleteCategoryResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                in: 'cookie',
                name: 'better-auth.session_token',
                type: 'apiKey',
            },
        ],
        url: '/api/households/{householdId}/categories/{categoryId}',
        ...options,
    });

export const categoryUpdateCategory = <ThrowOnError extends boolean = false>(
    options: Options<CategoryUpdateCategoryData, ThrowOnError>,
): RequestResult<CategoryUpdateCategoryResponses, unknown, ThrowOnError> =>
    (options.client ?? client).patch<
        CategoryUpdateCategoryResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                in: 'cookie',
                name: 'better-auth.session_token',
                type: 'apiKey',
            },
        ],
        url: '/api/households/{householdId}/categories/{categoryId}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

export const categoryDefaultsGetDefaultCategories = <
    ThrowOnError extends boolean = false,
>(
    options?: Options<CategoryDefaultsGetDefaultCategoriesData, ThrowOnError>,
): RequestResult<
    CategoryDefaultsGetDefaultCategoriesResponses,
    unknown,
    ThrowOnError
> =>
    (options?.client ?? client).get<
        CategoryDefaultsGetDefaultCategoriesResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                in: 'cookie',
                name: 'better-auth.session_token',
                type: 'apiKey',
            },
        ],
        url: '/api/categories/default',
        ...options,
    });

export const accountGetAccounts = <ThrowOnError extends boolean = false>(
    options: Options<AccountGetAccountsData, ThrowOnError>,
): RequestResult<AccountGetAccountsResponses, unknown, ThrowOnError> =>
    (options.client ?? client).get<
        AccountGetAccountsResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                in: 'cookie',
                name: 'better-auth.session_token',
                type: 'apiKey',
            },
        ],
        url: '/api/households/{householdId}/accounts',
        ...options,
    });

export const accountCreateAccount = <ThrowOnError extends boolean = false>(
    options: Options<AccountCreateAccountData, ThrowOnError>,
): RequestResult<AccountCreateAccountResponses, unknown, ThrowOnError> =>
    (options.client ?? client).post<
        AccountCreateAccountResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                in: 'cookie',
                name: 'better-auth.session_token',
                type: 'apiKey',
            },
        ],
        url: '/api/households/{householdId}/accounts',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

export const accountDeleteAccount = <ThrowOnError extends boolean = false>(
    options: Options<AccountDeleteAccountData, ThrowOnError>,
): RequestResult<AccountDeleteAccountResponses, unknown, ThrowOnError> =>
    (options.client ?? client).delete<
        AccountDeleteAccountResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                in: 'cookie',
                name: 'better-auth.session_token',
                type: 'apiKey',
            },
        ],
        url: '/api/households/{householdId}/accounts/{accountId}',
        ...options,
    });

export const accountUpdateAccount = <ThrowOnError extends boolean = false>(
    options: Options<AccountUpdateAccountData, ThrowOnError>,
): RequestResult<AccountUpdateAccountResponses, unknown, ThrowOnError> =>
    (options.client ?? client).patch<
        AccountUpdateAccountResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                in: 'cookie',
                name: 'better-auth.session_token',
                type: 'apiKey',
            },
        ],
        url: '/api/households/{householdId}/accounts/{accountId}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

export const onboardingOnboard = <ThrowOnError extends boolean = false>(
    options: Options<OnboardingOnboardData, ThrowOnError>,
): RequestResult<OnboardingOnboardResponses, unknown, ThrowOnError> =>
    (options.client ?? client).post<
        OnboardingOnboardResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                in: 'cookie',
                name: 'better-auth.session_token',
                type: 'apiKey',
            },
        ],
        url: '/api/households/onboarding',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

export const onboardingValidateHousehold = <
    ThrowOnError extends boolean = false,
>(
    options: Options<OnboardingValidateHouseholdData, ThrowOnError>,
): RequestResult<OnboardingValidateHouseholdResponses, unknown, ThrowOnError> =>
    (options.client ?? client).post<
        OnboardingValidateHouseholdResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                in: 'cookie',
                name: 'better-auth.session_token',
                type: 'apiKey',
            },
        ],
        url: '/api/households/onboarding/validate-household',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

export const onboardingValidateCategories = <
    ThrowOnError extends boolean = false,
>(
    options: Options<OnboardingValidateCategoriesData, ThrowOnError>,
): RequestResult<
    OnboardingValidateCategoriesResponses,
    unknown,
    ThrowOnError
> =>
    (options.client ?? client).post<
        OnboardingValidateCategoriesResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                in: 'cookie',
                name: 'better-auth.session_token',
                type: 'apiKey',
            },
        ],
        url: '/api/households/onboarding/validate-categories',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

export const onboardingValidateAccounts = <
    ThrowOnError extends boolean = false,
>(
    options: Options<OnboardingValidateAccountsData, ThrowOnError>,
): RequestResult<OnboardingValidateAccountsResponses, unknown, ThrowOnError> =>
    (options.client ?? client).post<
        OnboardingValidateAccountsResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                in: 'cookie',
                name: 'better-auth.session_token',
                type: 'apiKey',
            },
        ],
        url: '/api/households/onboarding/validate-accounts',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

export const transactionGetTransactions = <
    ThrowOnError extends boolean = false,
>(
    options: Options<TransactionGetTransactionsData, ThrowOnError>,
): RequestResult<TransactionGetTransactionsResponses, unknown, ThrowOnError> =>
    (options.client ?? client).get<
        TransactionGetTransactionsResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                in: 'cookie',
                name: 'better-auth.session_token',
                type: 'apiKey',
            },
        ],
        url: '/api/households/{householdId}/transactions',
        ...options,
    });

export const transactionCreateTransaction = <
    ThrowOnError extends boolean = false,
>(
    options: Options<TransactionCreateTransactionData, ThrowOnError>,
): RequestResult<
    TransactionCreateTransactionResponses,
    unknown,
    ThrowOnError
> =>
    (options.client ?? client).post<
        TransactionCreateTransactionResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                in: 'cookie',
                name: 'better-auth.session_token',
                type: 'apiKey',
            },
        ],
        url: '/api/households/{householdId}/transactions',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });

export const transactionDeleteTransaction = <
    ThrowOnError extends boolean = false,
>(
    options: Options<TransactionDeleteTransactionData, ThrowOnError>,
): RequestResult<
    TransactionDeleteTransactionResponses,
    unknown,
    ThrowOnError
> =>
    (options.client ?? client).delete<
        TransactionDeleteTransactionResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                in: 'cookie',
                name: 'better-auth.session_token',
                type: 'apiKey',
            },
        ],
        url: '/api/households/{householdId}/transactions/{transactionId}',
        ...options,
    });

export const transactionUpdateTransaction = <
    ThrowOnError extends boolean = false,
>(
    options: Options<TransactionUpdateTransactionData, ThrowOnError>,
): RequestResult<
    TransactionUpdateTransactionResponses,
    unknown,
    ThrowOnError
> =>
    (options.client ?? client).patch<
        TransactionUpdateTransactionResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                in: 'cookie',
                name: 'better-auth.session_token',
                type: 'apiKey',
            },
        ],
        url: '/api/households/{householdId}/transactions/{transactionId}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });
