// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type HealthDto = {
    status: string;
};

export type HouseholdDto = {
    id: string;
    name: string;
    role: 'owner' | 'member';
    onboardingComplete: boolean;
    /**
     * Currency of every account and transaction; changing it relabels them without converting amounts
     */
    baseCurrency: 'CHF' | 'EUR' | 'USD' | 'GBP';
    createdAt: string;
};

export type UpdateHouseholdDto = {
    name?: string;
    baseCurrency?: 'CHF' | 'EUR' | 'USD' | 'GBP';
};

export type CategoryDto = {
    id: string;
    name: string;
    createdAt: string;
    /**
     * Transactions assigned to this category
     */
    transactionCount: number;
};

export type CreateCategoryDto = {
    /**
     * Category name
     */
    name: string;
};

export type DefaultCategoryDto = {
    /**
     * category translation key
     */
    translateKey: string;
};

export type AccountDto = {
    id: string;
    householdId: string;
    /**
     * Per-household running number, starts at 1
     */
    number: number;
    description: string;
    type: 'checking' | 'savings' | 'cash' | 'credit_card' | 'other';
    currency: string;
    /**
     * Minor units (cents)
     */
    initialValue: number;
    /**
     * Minor units (cents)
     */
    amount: number;
    startDate: string;
    archivedAt: string | null;
    createdAt: string;
};

export type CreateAccountDto = {
    /**
     * Account description
     */
    description: string;
    type: 'checking' | 'savings' | 'cash' | 'credit_card' | 'other';
    currency: 'CHF' | 'EUR' | 'USD' | 'GBP';
    /**
     * Minor units (cents), negative for debt
     */
    initialValue: number;
    startDate: string;
};

export type UpdateAccountDto = {
    /**
     * Account description
     */
    description: string;
    type: 'checking' | 'savings' | 'cash' | 'credit_card' | 'other';
    currency: 'CHF' | 'EUR' | 'USD' | 'GBP';
    startDate: string;
    archivedAt?: string | null;
};

export type OnboardingAccountDto = {
    /**
     * Account description
     */
    description: string;
    type: 'checking' | 'savings' | 'cash' | 'credit_card' | 'other';
    currency: 'CHF' | 'EUR' | 'USD' | 'GBP';
    /**
     * Minor units (cents), negative for debt
     */
    initialValue: number;
    startDate: string;
};

export type CompleteOnboardingDto = {
    /**
     * Household name
     */
    name: string;
    categoryNames: Array<string>;
    accounts: Array<OnboardingAccountDto>;
};

export type OnboardingHouseholdDto = {
    /**
     * Household name
     */
    name: string;
};

export type OnboardingCategoriesDto = {
    categoryNames: Array<string>;
};

export type OnboardingAccountsDto = {
    accounts: Array<OnboardingAccountDto>;
};

export type TransactionDto = {
    id: string;
    accountId: string;
    categoryId: string | null;
    type: 'expense' | 'income';
    /**
     * Minor units (cents), positive; sign comes from type
     */
    amount: number;
    title: string | null;
    description: string | null;
    date: string;
    createdAt: string;
};

export type TransactionPageDto = {
    items: Array<TransactionDto>;
    /**
     * Matching rows across all pages
     */
    total: number;
    /**
     * 1-based
     */
    page: number;
    pageSize: number;
};

export type CurrencyStatsDto = {
    /**
     * Household currency
     */
    currency: string;
    /**
     * Minor units (cents)
     */
    income: number;
    /**
     * Minor units (cents)
     */
    expenses: number;
    /**
     * Minor units (cents), income - expenses
     */
    net: number;
};

export type CategoryExpenseDto = {
    categoryId: string | null;
    /**
     * Null for uncategorized entries
     */
    categoryName: string | null;
    /**
     * Minor units (cents) of `currency`
     */
    expenses: number;
};

export type CategoryStatsDto = {
    /**
     * Household currency
     */
    currency: string;
    /**
     * Sorted by expenses, descending
     */
    categories: Array<CategoryExpenseDto>;
};

export type CreateTransactionDto = {
    /**
     * Account id within the household
     */
    accountId: string;
    /**
     * Category id within the household
     */
    categoryId?: string | null;
    type: 'expense' | 'income';
    /**
     * Minor units (cents)
     */
    amount: number;
    title?: string | null;
    description?: string | null;
    date: string;
};

export type BudgetDto = {
    id: string;
    categoryId: string;
    /**
     * Calendar month as YYYY-MM
     */
    month: string;
    /**
     * Limit in minor units of the household currency. 0 is a deliberate zero limit.
     */
    amount: number;
};

export type SetBudgetDto = {
    /**
     * Limit in minor units of the household currency, 0 or more
     */
    amount: number;
};

export type CopiedBudgetsDto = {
    /**
     * Month the limits were taken from, or null when no earlier month had any
     */
    sourceMonth: string | null;
    budgets: Array<BudgetDto>;
    /**
     * True when an automatic take-over left the month alone because its limits were touched before
     */
    skipped: boolean;
};

export type HealthHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type HealthHealthResponses = {
    200: HealthDto;
};

export type HealthHealthResponse =
    HealthHealthResponses[keyof HealthHealthResponses];

export type HouseholdMineData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/households/me';
};

export type HouseholdMineResponses = {
    200: HouseholdDto;
};

export type HouseholdMineResponse =
    HouseholdMineResponses[keyof HouseholdMineResponses];

export type HouseholdUpdateHouseholdData = {
    body: UpdateHouseholdDto;
    path: {
        /**
         * Household id
         */
        householdId: string;
    };
    query?: never;
    url: '/api/households/{householdId}';
};

export type HouseholdUpdateHouseholdResponses = {
    200: HouseholdDto;
};

export type HouseholdUpdateHouseholdResponse =
    HouseholdUpdateHouseholdResponses[keyof HouseholdUpdateHouseholdResponses];

export type CategoryGetCategoriesData = {
    body?: never;
    path: {
        /**
         * Household id
         */
        householdId: string;
    };
    query?: never;
    url: '/api/households/{householdId}/categories';
};

export type CategoryGetCategoriesResponses = {
    200: Array<CategoryDto>;
};

export type CategoryGetCategoriesResponse =
    CategoryGetCategoriesResponses[keyof CategoryGetCategoriesResponses];

export type CategoryCreateCategoryData = {
    body: CreateCategoryDto;
    path: {
        /**
         * Household id
         */
        householdId: string;
    };
    query?: never;
    url: '/api/households/{householdId}/categories';
};

export type CategoryCreateCategoryResponses = {
    200: CategoryDto;
};

export type CategoryCreateCategoryResponse =
    CategoryCreateCategoryResponses[keyof CategoryCreateCategoryResponses];

export type CategoryDeleteCategoryData = {
    body?: never;
    path: {
        /**
         * Household id
         */
        householdId: string;
        /**
         * Category id
         */
        categoryId: string;
    };
    query?: {
        /**
         * Reassign the transactions to this category before deleting. Omitted: they become uncategorized.
         */
        transferTo?: string;
    };
    url: '/api/households/{householdId}/categories/{categoryId}';
};

export type CategoryDeleteCategoryResponses = {
    /**
     * Category successfully deleted
     */
    204: void;
};

export type CategoryDeleteCategoryResponse =
    CategoryDeleteCategoryResponses[keyof CategoryDeleteCategoryResponses];

export type CategoryUpdateCategoryData = {
    body: CreateCategoryDto;
    path: {
        /**
         * Household id
         */
        householdId: string;
        /**
         * Category id
         */
        categoryId: string;
    };
    query?: never;
    url: '/api/households/{householdId}/categories/{categoryId}';
};

export type CategoryUpdateCategoryResponses = {
    200: CategoryDto;
};

export type CategoryUpdateCategoryResponse =
    CategoryUpdateCategoryResponses[keyof CategoryUpdateCategoryResponses];

export type CategoryDefaultsGetDefaultCategoriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/categories/default';
};

export type CategoryDefaultsGetDefaultCategoriesResponses = {
    200: Array<DefaultCategoryDto>;
};

export type CategoryDefaultsGetDefaultCategoriesResponse =
    CategoryDefaultsGetDefaultCategoriesResponses[keyof CategoryDefaultsGetDefaultCategoriesResponses];

export type AccountGetAccountsData = {
    body?: never;
    path: {
        /**
         * Household id
         */
        householdId: string;
    };
    query?: never;
    url: '/api/households/{householdId}/accounts';
};

export type AccountGetAccountsResponses = {
    200: Array<AccountDto>;
};

export type AccountGetAccountsResponse =
    AccountGetAccountsResponses[keyof AccountGetAccountsResponses];

export type AccountCreateAccountData = {
    body: CreateAccountDto;
    path: {
        /**
         * Household id
         */
        householdId: string;
    };
    query?: never;
    url: '/api/households/{householdId}/accounts';
};

export type AccountCreateAccountResponses = {
    200: AccountDto;
};

export type AccountCreateAccountResponse =
    AccountCreateAccountResponses[keyof AccountCreateAccountResponses];

export type AccountDeleteAccountData = {
    body?: never;
    path: {
        /**
         * Household id
         */
        householdId: string;
        /**
         * Account id
         */
        accountId: string;
    };
    query?: never;
    url: '/api/households/{householdId}/accounts/{accountId}';
};

export type AccountDeleteAccountErrors = {
    /**
     * The account has transactions
     */
    409: unknown;
};

export type AccountDeleteAccountResponses = {
    204: void;
};

export type AccountDeleteAccountResponse =
    AccountDeleteAccountResponses[keyof AccountDeleteAccountResponses];

export type AccountUpdateAccountData = {
    body: UpdateAccountDto;
    path: {
        /**
         * Household id
         */
        householdId: string;
        /**
         * Account id
         */
        accountId: string;
    };
    query?: never;
    url: '/api/households/{householdId}/accounts/{accountId}';
};

export type AccountUpdateAccountResponses = {
    200: AccountDto;
};

export type AccountUpdateAccountResponse =
    AccountUpdateAccountResponses[keyof AccountUpdateAccountResponses];

export type OnboardingOnboardData = {
    body: CompleteOnboardingDto;
    path?: never;
    query?: never;
    url: '/api/households/onboarding';
};

export type OnboardingOnboardResponses = {
    200: HouseholdDto;
};

export type OnboardingOnboardResponse =
    OnboardingOnboardResponses[keyof OnboardingOnboardResponses];

export type OnboardingValidateHouseholdData = {
    body: OnboardingHouseholdDto;
    path?: never;
    query?: never;
    url: '/api/households/onboarding/validate-household';
};

export type OnboardingValidateHouseholdResponses = {
    /**
     * Household step values are valid
     */
    204: void;
};

export type OnboardingValidateHouseholdResponse =
    OnboardingValidateHouseholdResponses[keyof OnboardingValidateHouseholdResponses];

export type OnboardingValidateCategoriesData = {
    body: OnboardingCategoriesDto;
    path?: never;
    query?: never;
    url: '/api/households/onboarding/validate-categories';
};

export type OnboardingValidateCategoriesResponses = {
    /**
     * Categories step values are valid
     */
    204: void;
};

export type OnboardingValidateCategoriesResponse =
    OnboardingValidateCategoriesResponses[keyof OnboardingValidateCategoriesResponses];

export type OnboardingValidateAccountsData = {
    body: OnboardingAccountsDto;
    path?: never;
    query?: never;
    url: '/api/households/onboarding/validate-accounts';
};

export type OnboardingValidateAccountsResponses = {
    /**
     * Accounts step values are valid
     */
    204: void;
};

export type OnboardingValidateAccountsResponse =
    OnboardingValidateAccountsResponses[keyof OnboardingValidateAccountsResponses];

export type TransactionGetTransactionsData = {
    body?: never;
    path: {
        /**
         * Household id
         */
        householdId: string;
    };
    query?: {
        /**
         * Only this account
         */
        accountId?: string;
        /**
         * Only this category; "none" selects uncategorized rows
         */
        categoryId?: string;
        /**
         * 1-based
         */
        page?: number;
        /**
         * Rows per page
         */
        pageSize?: number;
    };
    url: '/api/households/{householdId}/transactions';
};

export type TransactionGetTransactionsResponses = {
    200: TransactionPageDto;
};

export type TransactionGetTransactionsResponse =
    TransactionGetTransactionsResponses[keyof TransactionGetTransactionsResponses];

export type TransactionCreateTransactionData = {
    body: CreateTransactionDto;
    path: {
        /**
         * Household id
         */
        householdId: string;
    };
    query?: never;
    url: '/api/households/{householdId}/transactions';
};

export type TransactionCreateTransactionResponses = {
    200: TransactionDto;
};

export type TransactionCreateTransactionResponse =
    TransactionCreateTransactionResponses[keyof TransactionCreateTransactionResponses];

export type TransactionGetStatsData = {
    body?: never;
    path: {
        /**
         * Household id
         */
        householdId: string;
    };
    query: {
        /**
         * Range start (inclusive)
         */
        from: string;
        /**
         * Range end (exclusive)
         */
        to: string;
    };
    url: '/api/households/{householdId}/transactions/stats';
};

export type TransactionGetStatsResponses = {
    200: CurrencyStatsDto;
};

export type TransactionGetStatsResponse =
    TransactionGetStatsResponses[keyof TransactionGetStatsResponses];

export type TransactionGetCategoryStatsData = {
    body?: never;
    path: {
        /**
         * Household id
         */
        householdId: string;
    };
    query: {
        /**
         * Range start (inclusive)
         */
        from: string;
        /**
         * Range end (exclusive)
         */
        to: string;
    };
    url: '/api/households/{householdId}/transactions/stats/categories';
};

export type TransactionGetCategoryStatsResponses = {
    200: CategoryStatsDto;
};

export type TransactionGetCategoryStatsResponse =
    TransactionGetCategoryStatsResponses[keyof TransactionGetCategoryStatsResponses];

export type TransactionDeleteTransactionData = {
    body?: never;
    path: {
        /**
         * Household id
         */
        householdId: string;
        /**
         * Transaction id
         */
        transactionId: string;
    };
    query?: never;
    url: '/api/households/{householdId}/transactions/{transactionId}';
};

export type TransactionDeleteTransactionResponses = {
    /**
     * Transaction successfully deleted
     */
    204: void;
};

export type TransactionDeleteTransactionResponse =
    TransactionDeleteTransactionResponses[keyof TransactionDeleteTransactionResponses];

export type TransactionUpdateTransactionData = {
    body: CreateTransactionDto;
    path: {
        /**
         * Household id
         */
        householdId: string;
        /**
         * Transaction id
         */
        transactionId: string;
    };
    query?: never;
    url: '/api/households/{householdId}/transactions/{transactionId}';
};

export type TransactionUpdateTransactionResponses = {
    200: TransactionDto;
};

export type TransactionUpdateTransactionResponse =
    TransactionUpdateTransactionResponses[keyof TransactionUpdateTransactionResponses];

export type BudgetGetBudgetsData = {
    body?: never;
    path: {
        /**
         * Household id
         */
        householdId: string;
    };
    query: {
        /**
         * Calendar month as YYYY-MM
         */
        month: string;
    };
    url: '/api/households/{householdId}/budgets';
};

export type BudgetGetBudgetsResponses = {
    200: Array<BudgetDto>;
};

export type BudgetGetBudgetsResponse =
    BudgetGetBudgetsResponses[keyof BudgetGetBudgetsResponses];

export type BudgetDeleteBudgetData = {
    body?: never;
    path: {
        /**
         * Household id
         */
        householdId: string;
        /**
         * Category id
         */
        categoryId: string;
        /**
         * Calendar month as YYYY-MM
         */
        month: string;
    };
    query?: never;
    url: '/api/households/{householdId}/budgets/{categoryId}/{month}';
};

export type BudgetDeleteBudgetResponses = {
    /**
     * Budget removed; the category has no limit for that month
     */
    204: void;
};

export type BudgetDeleteBudgetResponse =
    BudgetDeleteBudgetResponses[keyof BudgetDeleteBudgetResponses];

export type BudgetSetBudgetData = {
    body: SetBudgetDto;
    path: {
        /**
         * Household id
         */
        householdId: string;
        /**
         * Category id
         */
        categoryId: string;
        /**
         * Calendar month as YYYY-MM
         */
        month: string;
    };
    query?: never;
    url: '/api/households/{householdId}/budgets/{categoryId}/{month}';
};

export type BudgetSetBudgetResponses = {
    200: BudgetDto;
};

export type BudgetSetBudgetResponse =
    BudgetSetBudgetResponses[keyof BudgetSetBudgetResponses];

export type BudgetCopyPreviousBudgetsData = {
    body?: never;
    path: {
        /**
         * Household id
         */
        householdId: string;
        /**
         * Calendar month as YYYY-MM
         */
        month: string;
    };
    query?: {
        /**
         * Take-over on first view: does nothing when the limits of the month were set, removed or taken over before
         */
        auto?: boolean;
    };
    url: '/api/households/{householdId}/budgets/{month}/copy-previous';
};

export type BudgetCopyPreviousBudgetsErrors = {
    /**
     * The month already has limits
     */
    409: unknown;
};

export type BudgetCopyPreviousBudgetsResponses = {
    /**
     * The month now holds copies of the nearest earlier month with limits; empty when there is none
     */
    200: CopiedBudgetsDto;
};

export type BudgetCopyPreviousBudgetsResponse =
    BudgetCopyPreviousBudgetsResponses[keyof BudgetCopyPreviousBudgetsResponses];
