// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type HouseholdDto = {
    id: string;
    name: string;
    currency: string;
    role: 'owner' | 'member';
    createdAt: string;
};

export type HouseholdMineData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/households/me';
};

export type HouseholdMineResponses = {
    200: HouseholdDto;
};

export type HouseholdMineResponse =
    HouseholdMineResponses[keyof HouseholdMineResponses];
